{% set name = "emsdk" %}
{% set version = "3.1.37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/emscripten-core/emsdk/archive/{{ version }}.tar.gz
  sha256: c3c80dfe82fb448751d1c48200e5143aeca0f0db1d021db4b63655a9d9470cd8

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python
    - nodejs

test:
  commands:
    - test -f ${PREFIX}/lib/python$PY_VER/site-packages/emsdk/__init__.py                                        # [unix]
    - test -f ${PREFIX}/lib/python$PY_VER/site-packages/emsdk/emsdk.py                                           # [unix]
    - if not exist %PREFIX%\\lib\\site-packages\\emsdk\\__init__.py (exit 1)                                     # [win]
    - if not exist %PREFIX%\\lib\\site-packages\\emsdk\\emsdk.py (exit 1)                                        # [win]
    - emsdk help
    - emsdk install 3.1.2
    - emsdk activate 3.1.2
    - if not exist %PREFIX%\\lib\\site-packages\\emsdk\\upstream\\emscripten\\tools\\file_packager.py (exit 1)   # [win]
    - test -f ${PREFIX}/lib/python$PY_VER/site-packages/emsdk/upstream/emscripten/tools/file_packager.py         # [unix]
    - python -c "import emsdk.upstream.emscripten.tools.file_packager"

about:
  home: https://github.com/emscripten-core/emsdk
  summary: Emscripten SDK
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/emscripten-core/emsdk

extra:
  recipe-maintainers:
    - martinRenou
